spring.application.name=fintrack

# H2 In-Memory Database (no installation needed)
spring.datasource.url=jdbc:h2:file:./fintrack-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 web console (optional - view your data at http://localhost:8080/h2-console)
spring.h2.console.enabled=true